import resend

from app.config import get_settings

settings = get_settings()


def _build_email_html(brief_id: str, insights: list[dict], period_start: str, period_end: str) -> str:
    rows = ""
    for insight in insights:
        evidence_links = " · ".join(
            f'<a href="{e["url"]}">{e["source_id"]}</a>'
            for e in insight.get("evidence", [])
            if e.get("url")
        )
        rows += f"""
        <div style="margin-bottom:32px;padding:20px;background:#f9fafb;border-radius:8px;">
          <p style="margin:0 0 4px;font-size:12px;color:#6b7280;">#{insight["rank"]} · Confidence {int(insight["confidence"] * 100)}%</p>
          <h2 style="margin:0 0 8px;font-size:18px;color:#111827;">{insight["title"]}</h2>
          <p style="margin:0 0 12px;color:#374151;">{insight["explanation"]}</p>
          <p style="margin:0 0 8px;"><strong>Action:</strong> {insight["suggested_action"]}</p>
          {f'<p style="margin:0;font-size:12px;color:#6b7280;">Sources: {evidence_links}</p>' if evidence_links else ""}
        </div>"""

    return f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;padding:32px 16px;">
      <h1 style="font-size:24px;font-weight:700;color:#111827;margin-bottom:4px;">Signal Intelligence Brief</h1>
      <p style="color:#6b7280;margin-bottom:32px;">{period_start} – {period_end}</p>
      {rows}
      <p style="font-size:12px;color:#9ca3af;margin-top:32px;">
        Generated by Signal · <a href="http://localhost:3000/briefs/{brief_id}">View in app</a>
      </p>
    </div>"""


def send_brief_email(
    recipient: str,
    brief_id: str,
    insights: list[dict],
    period_start: str,
    period_end: str,
) -> str:
    """Send the brief as an email. Returns the Resend message ID."""
    resend.api_key = settings.resend_api_key if hasattr(settings, "resend_api_key") else ""

    params = resend.Emails.SendParams(
        from_="Signal <briefs@signal.app>",
        to=[recipient],
        subject=f"Your Signal Brief — {period_start}",
        html=_build_email_html(brief_id, insights, period_start, period_end),
    )

    response = resend.Emails.send(params)
    return response["id"]
