"""add clerk_id to users

Revision ID: 1df21e0b607b
Revises: cc441d76abde
Create Date: 2026-05-08 20:27:09.890205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df21e0b607b'
down_revision: Union[str, Sequence[str], None] = 'cc441d76abde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###
