"""add_pulse_fields_to_feed_items

Revision ID: 4e0e576f4929
Revises: fd09b2ab17f2
Create Date: 2026-05-09 18:06:36.033038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0e576f4929'
down_revision: Union[str, Sequence[str], None] = 'fd09b2ab17f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight_feed_items', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('insight_feed_items', sa.Column('ticket_count', sa.Integer(), nullable=True))
    op.add_column('insight_feed_items', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('idx_feed_org_expires', 'insight_feed_items', ['org_id', sa.literal_column('expires_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feed_org_expires', table_name='insight_feed_items')
    op.drop_column('insight_feed_items', 'expires_at')
    op.drop_column('insight_feed_items', 'ticket_count')
    op.drop_column('insight_feed_items', 'category')
    # ### end Alembic commands ###
