"""add_category_affected_count_to_insights

Revision ID: c415207d3cc8
Revises: 1df21e0b607b
Create Date: 2026-05-09 16:30:03.217642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c415207d3cc8'
down_revision: Union[str, Sequence[str], None] = '1df21e0b607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('insights', sa.Column('affected_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'affected_count')
    op.drop_column('insights', 'category')
    # ### end Alembic commands ###
