"""make_raw_event_id_nullable_on_evidence_refs

Revision ID: fd09b2ab17f2
Revises: c415207d3cc8
Create Date: 2026-05-09 17:08:49.911961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd09b2ab17f2'
down_revision: Union[str, Sequence[str], None] = 'c415207d3cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence_refs', 'raw_event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('evidence_refs_raw_event_id_fkey'), 'evidence_refs', type_='foreignkey')
    op.create_foreign_key(None, 'evidence_refs', 'raw_events', ['raw_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_refs', type_='foreignkey')
    op.create_foreign_key(op.f('evidence_refs_raw_event_id_fkey'), 'evidence_refs', 'raw_events', ['raw_event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('evidence_refs', 'raw_event_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
